### ISSUE TITLE
All the Users on the project with Contributor role are unable to see the 'Voting' page with the list of Stories to Vote

### ISSUE THREAD

**Issue by SriVeeramachaneni** [AITGmbH/AIT.VotingExtension#108]
Using Chrome browser in both cases:

Users with Contributor role see the page this way - no data displays:
![image](https://user-images.githubusercontent.com/78116097/185997590-bf636e22-9f62-4c7f-ae27-650e8f9df9f8.png)

Where as Admins can see the page this way with the list of Stories that come-up as part of a Shared Query.
![image](https://user-images.githubusercontent.com/78116097/185997794-01b17ed4-b841-4a7d-995c-c4a91bbc3ed0.png)

Verified Shared Query access privileges and it is accessible by Contributor role users.

**Comment by barbara-goeller** [comment]
Hi @SriVeeramachaneni,
Sorry to hear that the extension does not work for you. Unfortunately I have to inform you that we decided to no longer maintain the extension and therefore will archive this repository and withdraw the extension from the marketplace within the next days.
If you like to continue using the extension you can create a fork of our repository and then build and publish the extension on your own.

Best regards
Barbara

**Comment by barbara-goeller** [comment]
Won't fix this issue since the tool will no longer be maintained.

**Comment by SriVeeramachaneni** [comment]
Hi Barbara,
Is there any alternative add-on for Voting feature that you are aware of?

Regards,
Sri

**Comment by barbara-goeller** [comment]
Hi @SriVeeramachaneni,
Unfortunately there is no alternative for voting in Azure DevOps (as far as I know).

Best regards
Barbara
