### ISSUE TITLE
Configure voting period

### ISSUE THREAD

**Issue by florianbader** [AITGmbH/AIT.VotingExtension#15]
It should be possible to configure a start and end date and time (UTC?) for when the voting is active. This enables a fixed voting period.

As we can only check this in JavaScript, it's not necessary to prevent the user from abusing it and directly voting via JavaScript.

**Comment by BarbaraGoeller-AIT** [comment]
Included in [newest Release](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList)
