### ISSUE TITLE
Only 1 vote allowed if multiple votes per item not selected

### ISSUE THREAD

**Issue by hintbw** [AITGmbH/AIT.VotingExtension#22]
For a voting instance, I need the ability to set how many total votes a user should be able to get.

Independently of that, I should be able to choose whether to allow multiple votes for a single item AND how many votes on a single item would be allowed.

Currently, unless you allow multiple votes per item and set the votes per item to be the total number of votes that the admin wants the user to have, the user will only get 1 vote total for all of the items being votes on.

I have provided two images that illustrate my settings and what a user would see.

![2018-11-27 16_20_36-voting - boards](https://user-images.githubusercontent.com/7452113/49118243-d0e12b80-f260-11e8-985d-e0f3f1bcca39.png)
![2018-11-27 16_20_04-settings voting cap - settings](https://user-images.githubusercontent.com/7452113/49118244-d179c200-f260-11e8-91a1-811d6f0a551e.png)

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

Thanks for your input. We are currently implementing the possibility to restrict the number of votes per item if the option 'Multiple votes per item' is enabled. The feature will be included in the upcoming release.

Best regards
Barbara

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

Today we released a [new version of the extension](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList). The new release includes the possibility to configure not only the number of votes per item but also the number of votes per user. We would like to get any feedback about the new release from you.

Best regards
Barbara
