### ISSUE TITLE
Update backlog order based on votes doesn't actually change backlog order

### ISSUE THREAD

**Issue by hintbw** [AITGmbH/AIT.VotingExtension#24]
We voted on our list of backlog items and then clicked on the update backlog order and it didn't actually update the backlog order of the items. They remained in their same order. This is obviously undesired and defeats the purpose of using the voting extension for us (in large part - we worked around by taking screenshots of the order, but there isn't even a way to export the list of items with the vote data so we could preserve the order in some way).

**Comment by MTRH** [comment]
I experience the exact same issue.

**Comment by bugerry87** [comment]
![image](https://user-images.githubusercontent.com/15690072/51306037-adef1e80-1a3c-11e9-9017-c78201884055.png)
Did you press this button?

**Comment by bugerry87** [comment]
We need more information about your environment, please.

Product:			Azure DevOps Service / Azure DevOps Server (TFS)
(Version):			
Process Pattern:	Agile / Scrum / ICCM / Custom
Voting Level:		Features / Requirements / Bugs / ...		 	
Browser:			
(OS):				

[AIT_VoteExt_EnvForm.txt](https://github.com/AITGmbH/AIT.VotingExtension/files/2778098/AIT_VoteExt_EnvForm.txt)

**Comment by hintbw** [comment]
Azure DevOps service

Custom process based on scrum

Requirements (we have bugs as well as two custom work item types that also appear on the requirements backlog)

**Comment by BarbaraGoeller-AIT** [comment]
Hi Brett,

I think the 'Apply to backlog'-functionality does not work correctly in your scenario. since you do not have only requirements in your backlog but you do vote only on these. I'm sorry for any inconvenience. 
We currently implement some major improvements including to make the 'Apply to backlog'-functionality only available in valid scenarios. This will be included in the next release.

Best regards
Barbara

**Comment by BarbaraGoeller-AIT** [comment]
Hi Brett. Today we released a [new version](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList) of the extension which should solve the problem. Amongst other very cool new features, we introduced voting types: so from now on you can choose between backlog-based and (flat)query-based voting when creating a new one. For backlog-based votings you can apply the results after the voting is terminated and it should work correctly.  We would like to get any feedback from you.

Best regards
Barbara
