### ISSUE TITLE
Add a filter/criteria or query in work Items 

### ISSUE THREAD

**Issue by MTRH** [AITGmbH/AIT.VotingExtension#27]
A good feature would be to add a filter/criteria or query so the voting owner can control which Work Item the users can vote on.

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

We are currently implementing the possibility to create votings based on simple queries. So most probably the feature will be included in the upcoming release.

Best regards
Barbara

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

Today we released a [new version of the extension](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList). Amongst other very cool new features, we introduced voting types: so from now on you can choose between backlog-based and (flat shared) query-based voting when creating a new one. We would like to get any feedback from you.

Best regards
Barbara
