### ISSUE TITLE
Confirmation of "Terms of Use" not possible

### ISSUE THREAD

**Issue by cfs77** [AITGmbH/AIT.VotingExtension#32]
Hi,

after clicking the button "confirm" the dialog "Terms of Use" appears again.
The usage of the extension is not possible.

The Adminsitration page works.

I tried the extension on Azure DevOps Service and Azure Devops Server. 
The error exists in both versions.

Best regards
Carsten

**Comment by bugerry87** [comment]
Does your browser allow cookies?
Which browser do you use?

**Comment by cfs77** [comment]
Hi,

cookies are activated.
I tested the extension with Edge (17.17134) and Chrome (71.0.3578.98).

Best regards

**Comment by cfs77** [comment]
Hi, now it works. 
No changes by myself and I can't see any update of the extension.

**Comment by UliLimper** [comment]
Same issue at my side, DevOps Server 2019 onPrem
