### ISSUE TITLE
Terms of Use confirmation doesnt' register

### ISSUE THREAD

**Issue by pabrams** [AITGmbH/AIT.VotingExtension#36]
Hi, I'm trying the extension, downloaded from the marketplace, on TFS 2017 update 3.  When I click Confirm on the Terms of Use, it just re-opens the Terms of Use, and a message on the page says "Voting is disabled since the terms of use are not confirmed. To be able to vote refresh the page and confirm the terms of use in the upcoming dialog."   This is in Chrome

**Comment by pabrams** [comment]
Wow, this is interesting.  I don't get the disclaimer at all in IE, but in IE I can't "create a Voting" whereas in Chrome I can.   What's unfortunate is that IE still claims that "there is  no Voting" even after I successfully create one in Chrome.  So it seems like I can almost get the full functionality using a combination of the two browsers, but not quite.

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

Unfortunately I cannot reproduce this behaviour. The confirmation of terms of use makes use of cookies so please ensure that you have cookies enabled in your browser.

If it still does not work please provide some more information, like used browser and version.

Best regards
Barbara

**Comment by pabrams** [comment]
Cookies were/are enabled; this is on Chrome Version 71.0.3578.98 (Official Build) (64-bit)
![cookiecapture](https://user-images.githubusercontent.com/1376688/52140951-35828300-2622-11e9-858f-c8bc457fc07c.PNG)

**Comment by Thieum** [comment]
The same happens to me in Edge with TFS 2018.2 (  16.131.27701.1 )
I can setup voting, but when I try to access the voting page through the backlog, I get stuck in an infinite loop of accepting the terms of use.

Same issue in Chrome as well.

**Comment by Mistwetter** [comment]
I experience the same issue here on my TFS [16.131.28226.3 (Tfs2018.Update3.1)]
 with different browsers ( Chrome, Edge ,IE) on different accounts and Computers.

**Comment by BarbaraGoeller-AIT** [comment]
Today we released a [new version](https://github.com/AITGmbH/AIT.VotingExtension/releases/tag/v1.2.18326.21) of the extension which should solve the problem. The drawback is we no longer support Azure DevOps Server (formerly called TFS). If you still want to use the extension on Azure DevOps Server, you could get the source code from the repo, build it yourself and upload it, this should still work. We would like to get any feedback.

**Comment by mikegoatly** [comment]
I'm running into this with the latest version (I've only just installed it)

Every time I accept the terms of use, a new request is made to:

```
https://coeo.extmgmt.visualstudio.com/_apis/ExtensionManagement/InstalledExtensions/AITGmbH/asap-voting-aitgmb-de-production/Data/Scopes/Default/Current/Collections/**TENANTNAME**/Documents/asap-voting-aitgmb-de-production_ed05eba0-ce1d-4a01-b7a6-d7940aabb9bb
```

Which returns:
``` json
{
"$id": "1",
"innerException": null,
"message": "%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist",
"typeName": "Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi",
"typeKey": "DocumentCollectionDoesNotExistException",
"errorCode": 0,
"eventId": 3000
}
```

**Comment by mikegoatly** [comment]
My bad - you had stated that this only works in Chrome. I was using the latest Chromium-based Edge.
