### ISSUE TITLE
IE11 not supported?

### ISSUE THREAD

**Issue by pabrams** [AITGmbH/AIT.VotingExtension#38]
On IE 11.0.75, when I visit the 'Voting' tab, it's blank.  I see some errors including a SecurityError (something to do with the Confirm dialog? Which I don't see?) and "actualVoting is undefined":

Do you support IE?

**Comment by BarbaraGoeller-AIT** [comment]
Hi. Sorry for the very late answer. Today we released a [new version](https://github.com/AITGmbH/AIT.VotingExtension/releases/tag/v1.2.18326.21) of the extension which should solve the problems with the terms of use-dialog.  We do not support IE so please use Chrome for the extension. Furthermore the extension includes a bunch of new features, so we are happy to receive any feedback from you.
