### ISSUE TITLE
Export a summary of the voting from the admin page

### ISSUE THREAD

**Issue by florianbader** [AITGmbH/AIT.VotingExtension#41]
As a admin
I want to a summary of the voting results when stopping a voting
so that I can persist it or share it with other stakeholders

- When stopping a voting in the settings page a results summary is shown. This page is shown until a new voting is created.
- A button 'Create new voting' is shown, which allows to dispose the results and create a new voting (show normal settings page)
When the button is clicked a notification is shown with text 'When you create a new voting, the results of the last voting are discarded. If you need them, please copy them first.'
- A button 'Copy results to clipboard' is shown, which allows to copy the results as HTML (analog to copy function in backlog for selected items)
- All other buttons / content of the standard settings page is hidden

**Comment by BarbaraGoeller-AIT** [comment]
Included in [newest Release](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList)
