### ISSUE TITLE
Voting does not display assigned to

### ISSUE THREAD

**Issue by florianbader** [AITGmbH/AIT.VotingExtension#47]
The work item System.AssignedTo field seems to return a string which causes the display name to be undefined:

![image](https://user-images.githubusercontent.com/1032945/54126981-0f15eb80-4409-11e9-9521-394b3768322c.png)

Check if the field value is a string and return the string instead otherwise check for the displayName property.

**Comment by BarbaraGoeller-AIT** [comment]
Solved in [neweset Release](https://github.com/AITGmbH/AIT.VotingExtension/releases/tag/v1.2.18326.21)
