### ISSUE TITLE
Bug - Cannot vote in ADO

### ISSUE THREAD

**Issue by TonyCurtisLives** [AITGmbH/AIT.VotingExtension#64]
Created a new voting session, with a start date from now till 24hrs from now. Could not vote. Widened the date range, still could not vote.

**Comment by cammurray** [comment]
Same issue. Can't vote on items.

The "green arrow" comes up allowing you to vote, but pressing on it does nothing.

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

Thanks for your input. I could reproduce the issue in Chrome and we plan to fix it within the next weeks. 
In the meantime you could use Microsoft Edge as browser in order to vote. Though it is not an officially supported browser for the extension it should work there.

Best regards
Barbara

**Comment by cammurray** [comment]
@BarbaraGoeller-AIT  can confirm the work around at the moment is to use Edge (traditional). It's broken in the chromium edge.

**Comment by florianbader** [comment]
@cammurray We released a new version today which fixes the issue.
