### ISSUE TITLE
Any way to get latest version to install on On Premise server?

### ISSUE THREAD

**Issue by mtavares628** [AITGmbH/AIT.VotingExtension#78]
Is there any way to get the latest version of this extension to work with an On Premise TFS 2017 server?  I'd love to take advantage of the feature to vote by the Work Item Query Type, but we have no plans to move to Azure DevOps Services in the immediate future.

Thanks,
Mike

**Comment by BarbaraGoeller-AIT** [comment]
Hi Mike,

Sorry for the late answer. As stated we do not officially support Azure DevOps Server. But if you want to still use the extension you can take the code, adapt it to make it work for your Azure DevOps version, package it and [upload it](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops-2019).

If you need help doing this you can contact [AIT sales](mailto:ait.vertrieb@aitgmbh.de).

Best regards
Barbara
