### ISSUE TITLE
Support for VSTS new UI

### ISSUE THREAD

**Issue by hintbw** [AITGmbH/AIT.VotingExtension#8]
It doesn't appear that the extension supports the new UI for Azure DevOps. Are there any plans to update it to work with the new UI, or is that something you are looking for contributions in order to make happen?

It looks like this particular extension is no longer listed on the company's tools for "TFS" from what I can see, so in looking to release this under an MIT license is the company backing away from offering this particular tool?

**Comment by BarbaraGoeller-AIT** [comment]
Hi,

First of all thanks a lot for your offer to contribute. The support for the new navigation in Azure DevOps is already implemented and will be part of the next release.

There are no plans to back away from the tool.

Best regards
Barbara

**Comment by BarbaraGoeller-AIT** [comment]
We resolved the issue in [Release 1.2.18326.21](https://github.com/AITGmbH/AIT.VotingExtension/releases/tag/v1.2.18326.21)
