### ISSUE TITLE
Add icon for new navigation

### ISSUE THREAD

**Issue by florianbader** [AITGmbH/AIT.VotingExtension#9]
We need an icon for the new navigation in Azure DevOps (backlog and admin page).

![image](https://user-images.githubusercontent.com/1032945/47622511-0b429600-db06-11e8-93e0-4f12cfd342f8.png)

**Comment by BarbaraGoeller-AIT** [comment]
Included in [newest Release](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production&targetId=edb2ce2e-5da5-4e22-9ce6-ee7a728bf53b&utm_source=vstsproduct&utm_medium=ExtHubManageList)
